# Generated by Django 4.2 on 2023-10-17 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('positive', models.DecimalField(decimal_places=2, max_digits=4)),
                ('negative', models.DecimalField(decimal_places=2, max_digits=4)),
                ('neutral', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realworld.analysis')),
            ],
        ),
    ]
