# Generated by Django 4.2 on 2023-10-17 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realworld', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
