# Generated by Django 4.2 on 2023-10-17 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realworld', '0002_rename_name_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=None, max_length=20, validators=[django.core.validators.MinLengthValidator(6)]),
            preserve_default=False,
        ),
    ]
