# Generated by Django 4.2 on 2023-10-17 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realworld', '0003_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
