# Generated by Django 4.2 on 2023-10-17 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realworld', '0004_remove_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=None, max_length=20, validators=[django.core.validators.MinLengthValidator(6)]),
            preserve_default=False,
        ),
    ]
